### ISSUE TITLE
Errors in Grafana Dashboards

### ISSUE THREAD

**Issue by survivant** [openebs/charts#196]
I imported the latest GF dashboard, "updated the datasource to : Prometheus"

I have this error in  : **localpv-dashboard**

http://10.1.7.114:30006/d/2e59785a-af05-465e-b9a3-fca65a0e8572/localpv-dashboard?orgId=1
![image](https://user-images.githubusercontent.com/191879/107984132-426a3900-6f95-11eb-9fb9-3a1aa0a6642c.png)

````
<html> <head> <script> window.onload = load('','','','',''); function getCell(name, value) { return "
"+name+"
"+value+"
"; } function load(volumeStr,pvcNameStr,namespaceStr,storageClassStr,typeStr) { var volumeStr = volumeStr.replace( /[{}]/g, '' ); var pvcNameStr = pvcNameStr.replace( /[{}]/g, '' ); var namespaceStr = namespaceStr.replace( /[{}]/g, '' ); var storageClassStr = storageClassStr.replace( /[{}]/g, '' ); var typeStr = typeStr.replace( /[{}]/g, '' ); // var pools = poolsStr.replace( /[{}]/g, '' ); // var rc = replicaCount.replace( /[{}]/g, '' ); // if(!rc) { // rc = "none"; // } // var uptimes = uptime.replace( /[{}]/g, '' ); // if(uptimes) { // var seconds = parseInt(uptimes, 10); // var days = Math.floor(seconds / (3600*24)); // seconds -= days*3600*24; // var hrs = Math.floor(seconds / 3600); // seconds -= hrs*3600; // var mnts = Math.floor(seconds / 60); // seconds -= mnts*60; // uptimes = days+" days, "+hrs+" Hrs, "+mnts+" Mins, "+seconds+" Secs"; // } // else { // uptimes = "No Data"; // } z=""; z+=getCell("PVC", pvcNameStr); z+=getCell("Namespace", namespaceStr); z+=getCell("CAS Type", typeStr); z+=getCell("Storage Class", storageClassStr); //z+=getCell("Name", volName); //z+=getCell("Pool Name", pools); //z+=getCell("No. of Replicas", rc); //z+=getCell("","") document.getElementById("volume-info").innerHTML = z; } </script> </head> <body>
</body> </html>
````

in : **storage-class-volume-dashboard**
http://10.1.7.114:30006/d/2795676f-d98f-4ba5-b424-b8b0e98ad7bd/storage-class-volume-dashboard?orgId=1&refresh=1m

![image](https://user-images.githubusercontent.com/191879/107984336-b86ea000-6f95-11eb-9772-efdb772aa9b6.png)

there are no storage class in the dropbox, but I have a few in my cluster

````
root@test-pcl114:~# kubectl get sc
NAME                        PROVISIONER                                                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
openebs-cstor-sparse        openebs.io/provisioner-iscsi                               Delete          Immediate              false                  27d
openebs-device              openebs.io/local                                           Delete          WaitForFirstConsumer   false                  88d
openebs-hostpath            openebs.io/local                                           Delete          WaitForFirstConsumer   false                  88d
openebs-jiva-default        openebs.io/provisioner-iscsi                               Delete          Immediate              false                  88d
openebs-snapshot-promoter   volumesnapshot.external-storage.k8s.io/snapshot-promoter   Delete          Immediate              false                  88d
sc-iep-localpv              cstor.csi.openebs.io                                       Delete          Immediate              true                   83d
sc-iep-mirror               cstor.csi.openebs.io                                       Delete          Immediate              true                   87d
sc-minio                    cstor.csi.openebs.io                                       Delete          WaitForFirstConsumer   true                   87d
sc-rocketchat               cstor.csi.openebs.io                                       Delete          Immediate              true                   86d
root@test-pcl114:~#

````

In **storage-pool-claim-dashboard**
http://10.1.7.114:30006/d/23c14553-6c62-41b6-9eb3-c0e75531e617/storage-pool-claim-dashboard?orgId=1
![image](https://user-images.githubusercontent.com/191879/107984468-fb307800-6f95-11eb-89bf-edf75994558c.png)

````
root@test-pcl114:~# kubectl get cspc -n openebs
NAME               HEALTHYINSTANCES   PROVISIONEDINSTANCES   DESIREDINSTANCES   AGE
cspc-iep-localpv   1                  1                      1                  83d
cspc-iep-mirror    1                  1                      1                  87d
cspc-minio         1                  1                      1                  87d
cspc-rocketchat    1                  1                      1                  87d
root@test-pcl114:~#

````

In **storage-pool-dashboard**
http://10.1.7.114:30006/d/5d86b1fd-b2e7-4bb2-befa-4dae5b6167d6/storage-pool-dashboard?orgId=1

![image](https://user-images.githubusercontent.com/191879/107984541-21561800-6f96-11eb-9642-fa0b8b89e817.png)

````
<html> <head> <script> window.onload = load('', '',''); function getCell(name, value) { return "
"+name+"
"+value+"
````

in **volume-tiled-view-dashboard**
http://10.1.7.114:30006/d/f46a2d03-c2af-4954-b2b3-307c4d77bcaf/volume-tiled-view-dashboard?orgId=1&refresh=1m
![image](https://user-images.githubusercontent.com/191879/107984620-51052000-6f96-11eb-988b-1e6890d4b03c.png)

````
<html> <head> <script> window.onload = load('', '', '', ' 1', ' 1143714'); function getCell(name, value) { return "
"+name+"
"+value+"
````

**Comment by survivant** [comment]
I think all the html errors are because I didn't pass the variable in the URL.  I think we should have a dropdown with the information instead of having to pass them in the URL.

**Comment by akhilerm** [comment]
cc: @Ab-hishek

**Comment by Ab-hishek** [comment]
I would need a few clarifications first @survivant .
1. How did you setup prometheus and grafana in your cluster? And how did you define your prometheus configs for pools metrics?
2. Which version of grafana are you running?

> I think all the html errors are because I didn't pass the variable in the URL. I think we should have a dropdown with the information instead of having to pass them in the URL.
Answering your concern about this. No, the errors are not w.r.t URL(except for localpv dashboard and storage pool dashboard). I think it is because of the grafana version being used. Also the null values I suspect are due the prometheus configs applied differently then expected. Thus wanted to know the way you defined the prometheus configs.

Regarding the storage class dashboard issue I will have to investigate it.

> The people that will mostly use those dashboard will be devops, but in my case.. the first level of support won't have access to the cluster. They have no idea what a pod is or where to get the information. So it not really possible to pass a URL what that information. The information should be available in dropdowns.. they will be able to select the right information and the board will update itself.
Will work on this.

Also will try to come up with the dashboard you requested.

**Comment by survivant** [comment]
@Ab-hishek I created a project here : https://github.com/survivant/openebs-grafana

My setup : 
On-premise
````
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

````
ctor - OpenEBS 2.6.0 (installed with Helm)

I'm using default Prometheus, AlertManager, Grafana (In the dependencies you will see kube-prometehus-stack.. I'm not using it anymore.. we are switching to default)

I added OpenEBS grafana dashboard in my chart and also I added dashboard that came from Prometheus-operator

Next step will be to import the rules from Prometheus-operator (from here : https://github.com/prometheus-operator/kube-prometheus/blob/master/manifests/kubernetes-prometheusRule.yaml )

**Comment by Ab-hishek** [comment]
What I meant is how did you apply the configs to let prometheus know from where to scrape the OpenEBS pools and volume related metrics? Like in the `openebs-monitoring-pg.yaml` which is present in the README.md file inside grafana-charts folder, prometheus scrape-configs are defined for openebs pools and volumes. There the labels like `openebs_io_cstor_pool_cluster` are replaced with other labels which is then used to form the dashboards. But in your case the labels are not getting replaced(as it is visible in the storage pool claim dashboard. If you see any of the metrics returned in the Used pool capacity panel) and hence the values are coming as null in the Text panel where HTML code in written.

**Comment by survivant** [comment]
I let Prometheus scrapes using the defaults.  I think it will scrape all pods that have the annotations: 
prometheus.io/path: /metrics
prometheus.io/port: 9500
prometheus.io/scrape: true

**Comment by Ab-hishek** [comment]
In that case I think you will need to replace the query in the dashboards templates with the original field name. For eg: 
replace `storage_pool_claim` with `openebs_io_cstor_pool_cluster`
replace `cstor_pool` with `openebs_io_cstor_pool_instance`
replace `openebs_pv` with `openebs_io_persistent_volume`
replace `openebs_pvc` with `openebs_io_persistent_volume_claim`

**Comment by survivant** [comment]
I see.  there are rules that were added in your prometheus config
````
- job_name: 'openebs-pools'
      scheme: http
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_openebs_io_monitoring]
        regex: pool_exporter_prometheus
        action: keep
        # Adding comma-separated source_labels below in order to fetch the metrics for pool claim instances of SPC and CSPC kind
      - source_labels: [__meta_kubernetes_pod_label_openebs_io_storage_pool_claim, __meta_kubernetes_pod_label_openebs_io_cstor_pool_cluster]
        action: replace
        # separator: Separator placed between concatenated source label values, default -> ;
        separator: ''
        target_label: storage_pool_claim
        # Adding comma-separated source_labels below in order to fetch the metrics for pool instances of CSP and CSPI kind
      - source_labels: [__meta_kubernetes_pod_label_openebs_io_cstor_pool, __meta_kubernetes_pod_label_openebs_io_cstor_pool_instance]
        action: replace
        # separator: Separator placed between concatenated source label values, default -> ;
        separator: ''
        target_label: cstor_pool
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: ${1}:${2}
        target_label: __address__
````

in my case I didn't use any new rules.  Using a vanilla Prometheus.
