### ISSUE TITLE
Grafana Dashboard for settings adjustments

### ISSUE THREAD

**Issue by survivant** [openebs/charts#207]
I'll look to have a dashboard that can help us to identify which drives can't handle the throughput or which ctor pool doesn't have enough resources to handle the "charge".

Let me explain in more details.

It's possible to configure the ctor pool with those settings

````
# values for the volumes
    volumes:
      queueDepth: 32
      luWorkers: 16
      zvolWorkers: 16
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      auxResources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
````

but it's possible that my settings are too low.  It will be useful to see in a dashboard /alerts to AlertManager too, that I have a ctor pool that is overloaded.  Not enough resources to handle all the requests.  Like a gauge or Health bar.. RED when it's overloaded.

same thing  when the pods are trying to write in a pool and the drives are not able to support it.. a RED health bar.. or a gauge : max throutpuyt supported / current.  Something that will tell us that the drives are overloaded and we need to reduce the speed that we write on them.. or change the pool to include another disk ?.. 

At this point, I changed the settings without knowing if it's too much are not enough.
