### ISSUE TITLE
param : os-disk-exclude-filter.exclude should be updatable

### ISSUE THREAD

**Issue by survivant** [openebs/charts#213]
We have this for the config map right now
````
filterconfigs:
      - key: os-disk-exclude-filter
        name: os disk exclude filter
        state: {{ .Values.ndm.filters.enableOsDiskExcludeFilter }}
        exclude: "/,/etc/hosts,/boot"
````
... {{ .Values.ndm.filters.enableOsDiskExcludeFilter }} should go for exclude and not for the state ?

````
filterconfigs:
      - key: os-disk-exclude-filter
        name: os disk exclude filter
        state: {{ .Values.ndm.filters.enableOsDiskState }}  // or not updatable at all
        exclude: {{ .Values.ndm.filters.enableOsDiskExcludeFilter }}  ///????
````
